all:
  vars:
    control_plane_endpoint: 192.168.1.100
    load_balancer_ip_pool:
      - 192.168.1.224/27
metal:
  children:
    masters:
      hosts:
        metal0: {ansible_host: 10.0.100.5, mac: '7c:d3:0a:1b:f2:7b', disk: sda, network_interface: eth01}
        metal1: {ansible_host: 10.0.100.6, mac: '00:8c:fa:d5:d0:7d', disk: sda, network_interface: eth01}
        metal2: {ansible_host: 10.0.100.7, mac: '7c:d3:0a:1d:a8:02', disk: sda, network_interface: eth01}
    workers:
      hosts: []
